### ISSUE TITLE
Doesn't render with JSON from raw Github files

### ISSUE THREAD

**Issue by richardtorres314** [MikeCoder/MJsonViewer#13]
**The Issue:**
The extension doesn't work with raw Github JSON files.

**Sample File:**
https://raw.githubusercontent.com/MikeCoder/MJsonViewer/master/manifest.json

**Comment by D0n9X1n** [comment]
Looks like a Firefox bug. It doesn't invoke scripts in plugin.
Do you know any plugin which works in this case?
I tried several plugins like [JSONViewer](https://jsonview.com/), [JSON Lite](https://addons.mozilla.org/en-US/firefox/addon/json-lite/?src=search). None of them works.

**Comment by richardtorres314** [comment]
I've tried nearly all add-ons available but none seem to do the trick. GitHub seems to render the JSON in a `pre` tag which seems different from most other sites loading JSON. Chrome's JSON Viewer extension seems to resolve this problem nicely, but I haven't looked at the code yet to see exactly what is being done in this circumstance.

**Comment by D0n9X1n** [comment]
Checked with Chrome, and it works fine. IMO this is a bug to Firefox, I have submitted this case to Mozilie, hope they can give a answer.

Due to that tag, Firefox applies a different workflow rather than the normal one(which will invoke plugins to handle the content). This is beyond what a plugin can do.

Anyway, I will use this weekend to look deeper to check if there is a workaround.

**Comment by richardtorres314** [comment]
I'll take a look as well and see if Firefox has any other cases like this. Thank you!
